export const operationText = {
  uploadDocument: ["Beleg hochladen", "Ladda upp dokument", "Upload document"],
  documentUploading: ["Beleg wird hochgeladen", "Dokument laddas upp", "Uploading document"],
  documentSaved: ["Beleg hochgeladen", "Dokument uppladdat", "Document uploaded"],
  documentFailed: ["Upload fehlgeschlagen (max. 25 MB). Für Belege ist eine Internetverbindung erforderlich.", "Uppladdning misslyckades (max. 25 MB). Dokument kräver internetanslutning.", "Upload failed (max. 25 MB). Documents require an internet connection."],
  retryUpload: ["Upload wiederholen", "Försök ladda upp igen", "Retry upload"],
  removeUpload: ["Ohne diesen Beleg fortfahren", "Fortsätt utan detta dokument", "Continue without this document"],
  purchase_receipts: ["Wareneingänge", "Varumottagningar", "Goods receipts"],
  maintenance_events: ["Wartungsverlauf", "Underhållshistorik", "Maintenance history"],
  actor: ["Benutzer", "Användare", "User"],
  historyFailed: ["Verlauf oder Beleg konnte nicht geladen werden.", "Historik eller dokument kunde inte hämtas.", "Could not load history or document."],
  maintenanceDueRequired: ["Bitte mindestens ein Fälligkeitsdatum, einen Kilometerstand oder Betriebsstunden angeben.", "Ange minst ett förfallodatum, en mätarställning eller drifttimmar.", "Enter at least one due date, mileage or operating-hours threshold."],
  suppliers: ["Lieferanten", "Leverantörer", "Suppliers"], supplier_contacts: ["Kontakte", "Kontakter", "Contacts"],
  purchase_orders: ["Bestellungen", "Beställningar", "Purchase orders"], purchase_order_items: ["Positionen", "Orderrader", "Order items"],
  resource_assignments: ["Zuordnungen", "Tilldelningar", "Assignments"], maintenance_plans: ["Wartungspläne", "Underhållsplaner", "Maintenance plans"],
  resource_details: ["Ausstattung", "Utrustning", "Equipment"], material_details: ["Beschaffung", "Inköpsuppgifter", "Purchasing details"], location_details: ["Standorte", "Lagerplatser", "Locations"],
  supplier_number: ["Lieferantennummer", "Leverantörsnummer", "Supplier number"], company: ["Unternehmen", "Företag", "Company"],
  name: ["Name", "Namn", "Name"], email: ["E-Mail", "E-post", "Email"], phone: ["Telefon", "Telefon", "Phone"], address: ["Adresse", "Adress", "Address"],
  vat_number: ["USt-ID", "Momsnummer", "VAT number"], payment_terms: ["Zahlungsbedingungen", "Betalningsvillkor", "Payment terms"], notes: ["Notizen", "Anteckningar", "Notes"],
  role: ["Rolle", "Roll", "Role"], order_number: ["Bestellnummer", "Ordernummer", "Order number"],
  supplier_id: ["Lieferant", "Leverantör", "Supplier"], preferred_supplier_id: ["Bevorzugter Lieferant", "Förvald leverantör", "Preferred supplier"],
  order_date: ["Bestelldatum", "Beställningsdatum", "Order date"], expected_delivery: ["Erwartete Lieferung", "Förväntad leverans", "Expected delivery"],
  location_id: ["Standort", "Lagerplats", "Location"], source_id: ["Von Standort", "Från lagerplats", "Source location"], destination_id: ["Nach Standort", "Till lagerplats", "Destination location"],
  job_id: ["Auftrag", "Uppdrag", "Job"], project_id: ["Projekt / Objekt", "Projekt / objekt", "Project / object"], resource_id: ["Ressource", "Resurs", "Resource"],
  employee_id: ["Mitarbeiter", "Medarbetare", "Employee"], responsible_person_id: ["Verantwortlich", "Ansvarig", "Responsible person"],
  currency: ["Währung", "Valuta", "Currency"], order_id: ["Bestellung", "Beställning", "Purchase order"], material_id: ["Material", "Material", "Material"],
  quantity: ["Menge", "Antal", "Quantity"], unit_price: ["Einzelpreis", "Styckpris", "Unit price"], starts_at: ["Beginn", "Start", "Start"], ends_at: ["Ende", "Slut", "End"],
  maintenance_type: ["Wartungsart", "Underhållstyp", "Maintenance type"], due_date: ["Fällig am", "Förfallodatum", "Due date"],
  due_mileage: ["Fällig bei km", "Förfaller vid km", "Due mileage"], due_hours: ["Fällig bei Betriebsstunden", "Förfaller vid drifttimmar", "Due operating hours"],
  interval_days: ["Intervall Tage", "Intervall dagar", "Interval days"], interval_mileage: ["Intervall km", "Intervall km", "Interval km"], interval_hours: ["Intervall Stunden", "Intervall timmar", "Interval hours"],
  equipment_kind: ["Ressourcenart", "Resurstyp", "Resource kind"], availability: ["Verfügbarkeit", "Tillgänglighet", "Availability"],
  purchase_date: ["Kaufdatum", "Inköpsdatum", "Purchase date"], purchase_price: ["Kaufpreis", "Inköpspris", "Purchase price"],
  warranty_until: ["Garantie bis", "Garanti till", "Warranty until"], warranty_notes: ["Garantiehinweise", "Garantivillkor", "Warranty notes"],
  operating_hours: ["Betriebsstunden", "Drifttimmar", "Operating hours"], reorder_quantity: ["Nachbestellmenge", "Beställningskvantitet", "Reorder quantity"],
  location_kind: ["Standortart", "Platstyp", "Location kind"], archived: ["Archiviert", "Arkiverad", "Archived"],
  completed_date: ["Abschlussdatum", "Slutförandedatum", "Completion date"], mileage: ["Kilometerstand", "Mätarställning", "Mileage"], cost: ["Kosten", "Kostnad", "Cost"],
  document_id: ["Dokumentreferenz", "Dokumentreferens", "Document reference"], note: ["Buchungsgrund", "Orsak", "Reason"],
  save: ["Speichern", "Spara", "Save"], cancel: ["Abbrechen", "Avbryt", "Cancel"], create: ["Neu", "Ny", "New"], edit: ["Bearbeiten", "Redigera", "Edit"],
  archive: ["Archivieren", "Arkivera", "Archive"], close: ["Schließen", "Stäng", "Close"],
  order: ["Bestellung absenden", "Markera som beställd", "Mark ordered"], cancelOrder: ["Bestellung stornieren", "Avbryt beställning", "Cancel order"],
  receive: ["Wareneingang", "Varumottagning", "Receive goods"], complete: ["Wartung abschließen", "Slutför underhåll", "Complete maintenance"],
  stock: ["Lagerbuchung", "Lagerbokning", "Stock movement"], waiting: ["Wartet auf Synchronisierung", "Väntar på synkronisering", "Waiting for sync"],
  failed: ["Nicht gespeichert / Konflikt", "Inte sparad / konflikt", "Not saved / conflict"],
  unavailable: ["Neue Module noch nicht verfügbar. Bestehende Lagerdaten bleiben unverändert.", "Nya moduler är inte tillgängliga. Befintliga lagerdata är oförändrade.", "New modules unavailable. Existing inventory data is unchanged."],
  empty: ["Keine Einträge", "Inga poster", "No records"], refresh: ["Aktualisieren", "Uppdatera", "Refresh"],
  previous: ["Vorherige Seite", "Föregående sida", "Previous page"], next: ["Nächste Seite", "Nästa sida", "Next page"],
  confirmArchive: ["Diesen Eintrag archivieren?", "Arkivera den här posten?", "Archive this record?"],
  vehicle: ["Fahrzeug", "Fordon", "Vehicle"], machine: ["Maschine", "Maskin", "Machine"], tool: ["Werkzeug", "Verktyg", "Tool"],
  equipment: ["Gerät", "Utrustning", "Equipment"], trailer: ["Anhänger", "Släp", "Trailer"], other: ["Sonstiges", "Övrigt", "Other"],
  available: ["Verfügbar", "Tillgänglig", "Available"], in_use: ["Im Einsatz", "I bruk", "In use"], maintenance: ["Wartung", "Underhåll", "Maintenance"],
  repair: ["Reparatur", "Reparation", "Repair"], unavailableStatus: ["Nicht verfügbar", "Otillgänglig", "Unavailable"],
  warehouse: ["Lager", "Lager", "Warehouse"], vehicleLocation: ["Fahrzeug", "Fordon", "Vehicle"], project: ["Projekt", "Projekt", "Project"],
  consumption: ["Materialverbrauch", "Materialförbrukning", "Material consumption"],
  start: ["Wartung beginnen", "Påbörja underhåll", "Start maintenance"],
  inProgress: ["In Wartung", "Under underhåll", "Maintenance in progress"],
  INVALID_OPERATIONS_COMMAND: ["Bitte Pflichtfelder, Mengen und Datumswerte prüfen.", "Kontrollera obligatoriska fält, antal och datum.", "Check required fields, quantities and dates."],
} as const;
export type OperationTextKey = keyof typeof operationText;
export function operationLabel(key: string, language: "de" | "sv" | "en") {
  const labels = operationText[key as OperationTextKey];
  return labels ? labels[language === "de" ? 0 : language === "sv" ? 1 : 2] : key;
}
